project_name            = "my-app"
aws_region              = "us-east-1"
vpc_cidr                = "10.0.0.0/16"
public_subnet_cidrs     = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs    = ["10.0.3.0/24", "10.0.4.0/24"]
azs                     = ["us-east-1a", "us-east-1b"]
instance_type           = "t3.micro"
db_name                 = "mydb"
db_username             = "admin"
db_password             = "mysecurepassword"
ssl_certificate_arn     = "arn:aws:acm:us-east-1:123456789012:certificate/xxxxxxx"
domain_name             = "example.com"
create_hosted_zone      = false
existing_zone_id        = "Z1234567890"